[build]
  base = ""
  publish = "client/dist"
  command = "npm --prefix client ci && npm --prefix client run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


